import type { Category, Product, User } from '../types';
import { hashPassword, KEYS, readStorage, uid, writeStorage } from '../utils/storage';

type DemoUser = User & { passwordHash: string };

const DEMO_USERS_KEY = 'nova_demo_users';
const now = () => new Date().toISOString();
const builtInUsers = [
  {
    id: 'demo-admin',
    name: 'Demo Administrator',
    email: 'admin@tienda.com',
    role: 'admin' as const,
    password: 'Administrador123*',
  },
  {
    id: 'demo-customer',
    name: 'Cliente Demo',
    email: 'cliente@tienda.com',
    role: 'customer' as const,
    password: 'Cliente123*',
  },
];

const demoCategories: Category[] = [
  { id: 'demo-cat-technology', name: 'Tecnología', slug: 'tecnologia', active: true, createdAt: now() },
  { id: 'demo-cat-accessories', name: 'Accesorios', slug: 'accesorios', active: true, createdAt: now() },
  { id: 'demo-cat-home', name: 'Hogar', slug: 'hogar', active: true, createdAt: now() },
  { id: 'demo-cat-wellness', name: 'Bienestar', slug: 'bienestar', active: true, createdAt: now() },
  { id: 'demo-cat-fashion', name: 'Moda', slug: 'moda', active: true, createdAt: now() },
  { id: 'demo-cat-beauty', name: 'Belleza', slug: 'belleza', active: true, createdAt: now() },
  { id: 'demo-cat-kitchen', name: 'Cocina', slug: 'cocina', active: true, createdAt: now() },
  { id: 'demo-cat-office', name: 'Oficina', slug: 'oficina', active: true, createdAt: now() },
  { id: 'demo-cat-outdoor', name: 'Aire libre', slug: 'aire-libre', active: true, createdAt: now() },
];

const demoProducts: Product[] = [
  {
    id: 'demo-product-headphones',
    defaultVariantId: 'demo-variant-headphones',
    name: 'Pulse Pro Headphones',
    description: 'Audífonos inalámbricos con cancelación de ruido, sonido envolvente y hasta 30 horas de batería.',
    category: 'Tecnología',
    categoryId: 'demo-cat-technology',
    price: 89.99,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-TECH-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-watch',
    defaultVariantId: 'demo-variant-watch',
    name: 'Urban Steel Watch',
    description: 'Reloj minimalista de acero inoxidable diseñado para uso diario.',
    category: 'Accesorios',
    categoryId: 'demo-cat-accessories',
    price: 64.5,
    stock: 11,
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-ACC-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-lamp',
    defaultVariantId: 'demo-variant-lamp',
    name: 'Aura Lamp',
    description: 'Lámpara de luz cálida regulable con una silueta contemporánea.',
    category: 'Hogar',
    categoryId: 'demo-cat-home',
    price: 39.5,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-HOME-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-yoga',
    defaultVariantId: 'demo-variant-yoga',
    name: 'Balance Yoga Kit',
    description: 'Set de yoga con mat antideslizante, bloque de apoyo y correa de estiramiento.',
    category: 'Bienestar',
    categoryId: 'demo-cat-wellness',
    price: 58.9,
    stock: 16,
    image: 'https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-WELL-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-speaker',
    defaultVariantId: 'demo-variant-speaker',
    name: 'Mini Sound Speaker',
    description: 'Parlante bluetooth compacto con sonido potente para escritorio, sala o viajes.',
    category: 'Tecnología',
    categoryId: 'demo-cat-technology',
    price: 42.99,
    stock: 24,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-TECH-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-keyboard',
    defaultVariantId: 'demo-variant-keyboard',
    name: 'Flow Wireless Keyboard',
    description: 'Teclado inalámbrico silencioso con diseño delgado para trabajo y estudio.',
    category: 'Tecnología',
    categoryId: 'demo-cat-technology',
    price: 54.9,
    stock: 14,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-TECH-003',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-power-bank',
    defaultVariantId: 'demo-variant-power-bank',
    name: 'ChargeGo Power Bank',
    description: 'Batería portátil de carga rápida para mantener tus dispositivos activos durante el día.',
    category: 'Tecnología',
    categoryId: 'demo-cat-technology',
    price: 34.99,
    stock: 32,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-TECH-004',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-backpack',
    defaultVariantId: 'demo-variant-backpack',
    name: 'City Carry Backpack',
    description: 'Mochila urbana resistente al agua con compartimento acolchado para laptop.',
    category: 'Accesorios',
    categoryId: 'demo-cat-accessories',
    price: 49.99,
    stock: 17,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-ACC-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-wallet',
    defaultVariantId: 'demo-variant-wallet',
    name: 'Slim Card Wallet',
    description: 'Billetera compacta para tarjetas y efectivo con acabado elegante.',
    category: 'Accesorios',
    categoryId: 'demo-cat-accessories',
    price: 24.5,
    stock: 28,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-ACC-003',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-sunglasses',
    defaultVariantId: 'demo-variant-sunglasses',
    name: 'Solace Sunglasses',
    description: 'Gafas de sol livianas con protección UV y estilo moderno.',
    category: 'Accesorios',
    categoryId: 'demo-cat-accessories',
    price: 36,
    stock: 19,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-ACC-004',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-throw',
    defaultVariantId: 'demo-variant-throw',
    name: 'Soft Home Throw',
    description: 'Manta decorativa suave para sala o dormitorio con textura premium.',
    category: 'Hogar',
    categoryId: 'demo-cat-home',
    price: 31.75,
    stock: 22,
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-HOME-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-candle',
    defaultVariantId: 'demo-variant-candle',
    name: 'Calm Scent Candle',
    description: 'Vela aromática con notas cálidas para crear ambientes relajados.',
    category: 'Hogar',
    categoryId: 'demo-cat-home',
    price: 18.9,
    stock: 36,
    image: 'https://images.unsplash.com/photo-1602874801007-bd458bb1b8b6?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-HOME-003',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-planter',
    defaultVariantId: 'demo-variant-planter',
    name: 'Ceramic Plant Pot',
    description: 'Maceta de cerámica con diseño limpio para plantas de interior.',
    category: 'Hogar',
    categoryId: 'demo-cat-home',
    price: 22.99,
    stock: 26,
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-HOME-004',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-bottle',
    defaultVariantId: 'demo-variant-bottle',
    name: 'Hydra Steel Bottle',
    description: 'Botella térmica de acero inoxidable para bebidas frías o calientes.',
    category: 'Bienestar',
    categoryId: 'demo-cat-wellness',
    price: 27.5,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-WELL-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-massage',
    defaultVariantId: 'demo-variant-massage',
    name: 'Relief Massage Roller',
    description: 'Rodillo de masaje para recuperación muscular después de entrenar.',
    category: 'Bienestar',
    categoryId: 'demo-cat-wellness',
    price: 29.9,
    stock: 21,
    image: 'https://images.unsplash.com/photo-1600881333168-2ef49b341f30?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-WELL-003',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-hoodie',
    defaultVariantId: 'demo-variant-hoodie',
    name: 'Everyday Cotton Hoodie',
    description: 'Hoodie de algodón suave con corte relajado para uso diario.',
    category: 'Moda',
    categoryId: 'demo-cat-fashion',
    price: 46.99,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-FASH-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-sneakers',
    defaultVariantId: 'demo-variant-sneakers',
    name: 'Nova Street Sneakers',
    description: 'Zapatillas casuales de diseño versátil para caminar con comodidad.',
    category: 'Moda',
    categoryId: 'demo-cat-fashion',
    price: 74.9,
    stock: 15,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-FASH-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-tote',
    defaultVariantId: 'demo-variant-tote',
    name: 'Canvas Market Tote',
    description: 'Bolso tote de lona para compras, universidad o salidas casuales.',
    category: 'Moda',
    categoryId: 'demo-cat-fashion',
    price: 21.5,
    stock: 33,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-FASH-003',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-skincare',
    defaultVariantId: 'demo-variant-skincare',
    name: 'Glow Skincare Set',
    description: 'Set básico de cuidado facial con limpiador, hidratante y sérum.',
    category: 'Belleza',
    categoryId: 'demo-cat-beauty',
    price: 52.9,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-BEAU-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-perfume',
    defaultVariantId: 'demo-variant-perfume',
    name: 'Luna Eau de Parfum',
    description: 'Fragancia fresca con notas florales y acabado elegante.',
    category: 'Belleza',
    categoryId: 'demo-cat-beauty',
    price: 69.99,
    stock: 13,
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-BEAU-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-coffee-maker',
    defaultVariantId: 'demo-variant-coffee-maker',
    name: 'Morning Brew Maker',
    description: 'Cafetera compacta para preparar café fresco en casa o en la oficina.',
    category: 'Cocina',
    categoryId: 'demo-cat-kitchen',
    price: 79.5,
    stock: 12,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-KIT-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-board',
    defaultVariantId: 'demo-variant-board',
    name: 'Bamboo Prep Board',
    description: 'Tabla de bambú resistente para preparar y servir alimentos.',
    category: 'Cocina',
    categoryId: 'demo-cat-kitchen',
    price: 25.9,
    stock: 29,
    image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-KIT-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-desk-organizer',
    defaultVariantId: 'demo-variant-desk-organizer',
    name: 'Focus Desk Organizer',
    description: 'Organizador de escritorio para mantener cables, notas y accesorios en orden.',
    category: 'Oficina',
    categoryId: 'demo-cat-office',
    price: 19.99,
    stock: 31,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-OFF-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-notebook',
    defaultVariantId: 'demo-variant-notebook',
    name: 'Ideas Hardcover Notebook',
    description: 'Cuaderno de tapa dura con papel grueso para notas, planes y bocetos.',
    category: 'Oficina',
    categoryId: 'demo-cat-office',
    price: 14.9,
    stock: 44,
    image: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-OFF-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-picnic',
    defaultVariantId: 'demo-variant-picnic',
    name: 'Weekend Picnic Blanket',
    description: 'Manta impermeable y plegable para parque, playa o viajes cortos.',
    category: 'Aire libre',
    categoryId: 'demo-cat-outdoor',
    price: 38.5,
    stock: 16,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-OUT-001',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-lantern',
    defaultVariantId: 'demo-variant-lantern',
    name: 'Trail LED Lantern',
    description: 'Linterna LED recargable para camping, emergencias y actividades al aire libre.',
    category: 'Aire libre',
    categoryId: 'demo-cat-outdoor',
    price: 33.99,
    stock: 23,
    image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?auto=format&fit=crop&w=900&q=80',
    featured: true,
    sku: 'NOVA-OUT-002',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-wireless-mouse',
    defaultVariantId: 'demo-variant-wireless-mouse',
    name: 'Swift Wireless Mouse',
    description: 'Mouse inalámbrico ergonómico con clic silencioso y precisión para trabajo diario.',
    category: 'Tecnología',
    categoryId: 'demo-cat-technology',
    price: 28.99,
    stock: 27,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-TECH-005',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-desk-lamp',
    defaultVariantId: 'demo-variant-desk-lamp',
    name: 'Focus LED Desk Lamp',
    description: 'Lámpara LED de escritorio con intensidad regulable para estudiar o trabajar mejor.',
    category: 'Oficina',
    categoryId: 'demo-cat-office',
    price: 37.9,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-OFF-003',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-french-press',
    defaultVariantId: 'demo-variant-french-press',
    name: 'Classic French Press',
    description: 'Prensa francesa de vidrio resistente para preparar café con sabor intenso.',
    category: 'Cocina',
    categoryId: 'demo-cat-kitchen',
    price: 32.5,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1521302080334-4bebac2763a6?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-KIT-003',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'demo-product-travel-mug',
    defaultVariantId: 'demo-variant-travel-mug',
    name: 'Everyday Travel Mug',
    description: 'Vaso térmico con tapa antiderrame para café, té o bebidas frías fuera de casa.',
    category: 'Aire libre',
    categoryId: 'demo-cat-outdoor',
    price: 23.99,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=900&q=80',
    featured: false,
    sku: 'NOVA-OUT-003',
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
];

export function getDemoCatalog() {
  return { categories: demoCategories, products: demoProducts };
}

export function isApiUnavailable(error: unknown) {
  return error instanceof TypeError || (error instanceof Error && /database|fetch|network|api/i.test(error.message));
}

export function registerDemoUser(name: string, email: string, password: string) {
  const users = readDemoUsers();
  const normalizedEmail = email.trim().toLowerCase();
  if (users.some((user) => user.email === normalizedEmail)) {
    throw new Error('An account with this email already exists.');
  }
  const role: User['role'] = normalizedEmail === 'admin@tienda.com' ? 'admin' : 'customer';
  const user: DemoUser = {
    id: uid('demo-user'),
    name: name.trim(),
    email: normalizedEmail,
    role,
    active: true,
    createdAt: now(),
    passwordHash: hashPassword(normalizeDemoPassword(password)),
  };
  writeDemoUsers([user, ...users]);
  writeStorage(KEYS.session, publicUser(user));
  return publicUser(user);
}

export function loginDemoUser(email: string, password: string) {
  const normalizedEmail = email.trim().toLowerCase();
  const user = readDemoUsers().find((candidate) => candidate.email === normalizedEmail);
  if (!user || user.passwordHash !== hashPassword(normalizeDemoPassword(password))) {
    throw new Error('Invalid email or password.');
  }
  if (!user.active) throw new Error('This account is not active.');
  writeStorage(KEYS.session, publicUser(user));
  return publicUser(user);
}

export function restoreDemoSession() {
  return readStorage<User | null>(KEYS.session, null);
}

export function logoutDemoUser() {
  localStorage.removeItem(KEYS.session);
}

function readDemoUsers(): DemoUser[] {
  const users = readStorage<DemoUser[]>(DEMO_USERS_KEY, []);
  const missingUsers = builtInUsers
    .filter((builtInUser) => !users.some((user) => user.email === builtInUser.email))
    .map<DemoUser>((builtInUser) => ({
      id: builtInUser.id,
      name: builtInUser.name,
      email: builtInUser.email,
      role: builtInUser.role,
      active: true,
      createdAt: now(),
      passwordHash: hashPassword(normalizeDemoPassword(builtInUser.password)),
    }));
  return [...missingUsers, ...users];
}

function writeDemoUsers(users: DemoUser[]) {
  writeStorage(DEMO_USERS_KEY, users);
}

function publicUser(user: DemoUser): User {
  const { passwordHash: _passwordHash, ...safeUser } = user;
  return safeUser;
}

function normalizeDemoPassword(password: string) {
  return password.trim();
}
