import type {CartItem,Order,OrderItem,PaymentMethod,Product,ShippingData,User} from '../types';import {apiRequest} from './apiClient';
export const roundMoney=(n:number)=>Number(n.toFixed(2));export function calculateOrder(items:Pick<OrderItem,'price'|'quantity'>[]){const subtotal=roundMoney(items.reduce((s,i)=>s+i.price*i.quantity,0)),tax=roundMoney(subtotal*.15);return{subtotal,tax,total:roundMoney(subtotal+tax)}}
type ApiPaymentMethod='CARD'|'BANK_TRANSFER'|'CASH_ON_DELIVERY';type ApiOrderStatus='PENDING_PAYMENT'|'PAID'|'PREPARING'|'READY_TO_SHIP'|'SHIPPED'|'DELIVERED'|'CANCELLED'|'REFUND_REQUESTED'|'REFUNDED'|'PAYMENT_FAILED';
type ApiShippingAddress={recipientName:string;phone:string;province:string;city:string;line1:string;reference?:string};
type ApiOrder={id:string;code:string;userId:string;customerName:string;customerEmail:string;createdAt:string;items:{productId:string;name:string;unitPrice:string|number;quantity:number}[];subtotal:string|number;tax:string|number;total:string|number;paymentMethod?:ApiPaymentMethod;shippingAddress:ApiShippingAddress;status:ApiOrderStatus;statusHistory:{status:ApiOrderStatus;createdAt:string}[];notes?:string};
const paymentToApi=(method:PaymentMethod):ApiPaymentMethod=>method==='Tarjeta'?'CARD':method==='Transferencia'?'BANK_TRANSFER':'CASH_ON_DELIVERY';
const statusFromApi=(status:ApiOrderStatus)=>status==='SHIPPED'||status==='READY_TO_SHIP'?'Enviado':status==='DELIVERED'?'Entregado':status==='PREPARING'||status==='PAID'?'Procesando':'Pendiente';
const paymentFromApi=(method?:ApiPaymentMethod):PaymentMethod=>method==='CARD'?'Tarjeta':method==='BANK_TRANSFER'?'Transferencia':'Contra entrega';
export async function createServerOrder(user:User,cart:CartItem[],products:Product[],shipping:ShippingData,paymentMethod:PaymentMethod,paymentReference?:string){const items=cart.map(item=>{const product=products.find(candidate=>candidate.id===item.productId);if(!product?.defaultVariantId)throw Error(`${product?.name??'Product'} is not available for checkout.`);return{variantId:product.defaultVariantId,quantity:item.quantity}});const notes=[shipping.notes,paymentReference?`Payment reference: ${paymentReference}`:undefined].filter(Boolean).join('\n');const order=await apiRequest<ApiOrder>('/orders',{method:'POST',body:JSON.stringify({items,shipping:{recipientName:shipping.fullName,phone:shipping.phone,province:shipping.province,city:shipping.city,line1:shipping.address,reference:shipping.notes},paymentMethod:paymentToApi(paymentMethod),customerEmail:shipping.email,notes})});return mapApiOrder(order,user,products,paymentMethod,paymentReference)}
function mapApiOrder(order:ApiOrder,user:User,products:Product[],fallbackPayment:PaymentMethod,paymentReference?:string):Order{return{id:order.code??order.id,userId:order.userId??user.id,customerName:order.customerName,customerEmail:order.customerEmail,createdAt:order.createdAt,items:order.items.map(item=>{const product=products.find(candidate=>candidate.id===item.productId);return{productId:item.productId,name:item.name,price:Number(item.unitPrice),quantity:item.quantity,image:product?.image??''}}),subtotal:Number(order.subtotal),tax:Number(order.tax),total:Number(order.total),paymentMethod:order.paymentMethod?paymentFromApi(order.paymentMethod):fallbackPayment,paymentReference,shipping:{fullName:order.shippingAddress.recipientName,email:order.customerEmail,phone:order.shippingAddress.phone,province:order.shippingAddress.province,address:order.shippingAddress.line1,city:order.shippingAddress.city,notes:order.shippingAddress.reference},status:statusFromApi(order.status),statusHistory:(order.statusHistory??[]).map(entry=>({status:statusFromApi(entry.status),date:entry.createdAt})),notes:order.notes}}
